### ISSUE TITLE
BQ E4.5 button can't be clicked 

### ISSUE THREAD

**Issue by delijati** [TronFortyTwo/OnTheRoad#2]
I tried to fix that in my fork https://github.com/delijati/OnTheRoad but unfortunately i could not find the reason. If i remove everything except the `Button` it works. So something is overlapping it i could not figure out what.

**Comment by TronFortyTwo** [comment]
The problem is the lag in the execution of the scripts, since they are executed directly. This can be fixed hopefully executing them throught QProcess(). Sadly I can't right now patch the app, but if you want to contribute I will be happy to merge your pull request :D

**Comment by TronFortyTwo** [comment]
You can see the documentation here http://doc.qt.io/qt-5/qprocess.html if you are interested

**Comment by delijati** [comment]
done
