### ISSUE TITLE
Apps not listed in libertine scope

### ISSUE THREAD

**Issue by delijati** [TronFortyTwo/OnTheRoad#4]
If we install directly from `bash` (in a chroot)  the corresponding file is not updated, so the apps are not listed in the `scope`
```
$ cat ~/.local/share/libertine/ContainersConfig.json
{
    "containerList": [
        {
            "InstallStatus": "ready",
            "InstalledApps": [],
            "distro": "vivid",
            "id": "conlibe",
            "multiarch": "disabled",
            "name": "OnTheRoad-conlibe",
            "type": "chroot"
        }
    ],
    "defaultContainer": "conlibe"
}

```

**Comment by delijati** [comment]
after installing it again with "libertine-container-manager install-package -p firefox" it works as the file was updated.

```
cat ~/.local/share/libertine/ContainersConfig.json
{
    "containerList": [
        {
            "InstallStatus": "ready",
            "InstalledApps": [],
            "distro": "vivid",
            "id": "conlibe",
            "installStatus": "ready",
            "installedApps": [
                {
                    "appStatus": "installed",
                    "packageName": "firefox"
                }
            ],
            "multiarch": "disabled",
            "name": "OnTheRoad-conlibe",
            "type": "chroot"
        }
    ],
    "defaultContainer": "conlibe"
}

```

**Comment by TronFortyTwo** [comment]
The installedApps section in the ContainersConfig.json file just show the apps installed by the "libertine-container-manager install-package" option to track which packages are installed, and remove them in the future with the remove-package option. The scope doesn't load the .desktop launchers reading from that file, so the app just installed with apt should appear in the scope. If it doesn't appear, have you tried refreshing the scope/rebooting?
