### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by NeoTheThird** [TronFortyTwo/OnTheRoad#5]
On my device the initial setup fails after issuing `otr-ssh` for the first time with the error `Permission denied (publickey)`. I think the reason for this is that is that i already had ssh keys on my device, but even after removing `.ssh/`, running `otr-ssh` errors out, so i might have fucked up some configs. If i have time i'll do more digging, but maybe you have an idea.

Thanks, and keep up the good work :)

**Comment by TronFortyTwo** [comment]
Yes, I found that behaviour in ut: with a fresh ssh configuration (empty ~/.ssh directory) sometimes work soemtimes not, I can't figure out why. What I do to make it work is: wipe .ssh directory, reboot then launch otr-ssh again; it should work.

**Comment by TronFortyTwo** [comment]
2.0.0 released with rework of the ssh loopback system, since I have not experienced this issue I close it. If it happens again with the updated version open it again :)

**Comment by NeoTheThird** [comment]
Awesome, thanks!
