### ISSUE TITLE
Dependency errors when installing stuffs via apt

### ISSUE THREAD

**Issue by kugiigi** [TronFortyTwo/OnTheRoad#7]
Step to reproduce:
1. Create a container
2. SSH to it and run the following command. (Not sure which package really causes the issue)
`apt-get install apt-utils build-essential cmake dpkg-cross fakeroot libc-dev isc-dhcp-client net-tools ifupdown g++ pkg-config ubuntu-sdk-libs ubuntu-sdk-libs-dev ubuntu-sdk-libs-tools oxideqt-codecs-extra qt5-doc language-pack-en click intltool python2.7 git cookiecutter`

3. Towards the end of installing and configuring, an error appears related to python2.7-minimal.

Device:
Nexus 5

Other observations/comments:
This does not happen in a container created via Libertine.
These packages by the way are needed for clickable to work directly on the device.

**Comment by TronFortyTwo** [comment]
Yes, I can reproduce it. As soon as possible I will regenerate the container to fix this.

**Comment by TronFortyTwo** [comment]
The new container I created for next release (2.0.0) is not affected anymore by this issue. :D

**Comment by TronFortyTwo** [comment]
2.0.0 released with the fix.
